### ISSUE TITLE
how to fix  'NoneType' object has no attribute 'image_encoder'

### ISSUE THREAD

**Issue by harkcc** [jhj0517/Layer-Divider-WebUI#2]
Traceback (most recent call last):
  File "D:\SAM\Layer-Divider-WebUI-master\venv\lib\site-packages\gradio\routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\SAM\Layer-Divider-WebUI-master\venv\lib\site-packages\gradio\blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "D:\SAM\Layer-Divider-WebUI-master\venv\lib\site-packages\gradio\blocks.py", line 1025, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\SAM\Layer-Divider-WebUI-master\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\SAM\Layer-Divider-WebUI-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\SAM\Layer-Divider-WebUI-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\SAM\Layer-Divider-WebUI-master\modules\sam.py", line 67, in generate_mask_app
    self.set_mask_generator()
  File "D:\SAM\Layer-Divider-WebUI-master\modules\sam.py", line 40, in set_mask_generator
    self.mask_generator = SamAutomaticMaskGenerator(
  File "D:\SAM\Layer-Divider-WebUI-master\venv\lib\site-packages\segment_anything\automatic_mask_generator.py", line 123, in __init__
    self.predictor = SamPredictor(model)
  File "D:\SAM\Layer-Divider-WebUI-master\venv\lib\site-packages\segment_anything\predictor.py", line 31, in __init__
    self.transform = ResizeLongestSide(sam_model.image_encoder.img_size)
AttributeError: 'NoneType' object has no attribute 'image_encoder'

**Comment by jhj0517** [comment]
it seems like Sam is not properly installed. 
I've just tested with latestest version and it works fine. 

If anyone still encounter this issue please let me know.

**Comment by jhj0517** [comment]
@RobetZyarde 
That would be torch version incompatibility issues, fixed in #6. 

But this project doesn't support prompt to the image and uses [sam](https://github.com/facebookresearch/segment-anything) instead of [sam-v2](https://github.com/facebookresearch/segment-anything-2), so it will be archived soon.

Can you try the new [sam2-playground](https://github.com/jhj0517/sam2-playground) repository instead?
There's also a feature to segment a video.
